document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/header.css\'>");
document.writeln("    <script src=\'../swiper/swiper-bundle.min.js\'></script>");
document.writeln("    <script src=\'../jquery-3.6.0.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../bootstrap/css/bootstrap.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../swiper/swiper-bundle.min.css\'>");
document.writeln("    ");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'header\'>");
document.writeln("    <div class=\'daohang\'>");
document.writeln("        <span class=\'btn2\'>");
document.writeln("                <button class=\'glyphicon glyphicon-menu-hamburger\'></button>");
document.writeln("          </span>");
document.writeln("        <span class=\'logo2\'>");
document.writeln("            <img src=\'../images/images_product/logo@2x.png\' alt=\'\'>");
document.writeln("        </span>");
document.writeln("        <span></span>");
document.writeln("    </div>");
document.writeln("    <div class=\'subnav\'>");
document.writeln("        <ul class=\'subnavleft\'>");
document.writeln("            <li class=\'current index\'>");
document.writeln("                <i class=\'is\'></i>");
document.writeln("                <a href=\'http://127.0.0.1:5500/index.html\' class=\'bg\'>首页</a>");
document.writeln("               ");
document.writeln("            </li>");
document.writeln("            <li class=\'product\'>");
document.writeln("                <i class=\'is\'></i>");
document.writeln("                <a href=\'#\'  class=\'bg\'>产品</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'deal\'>");
document.writeln("                <i class=\'is\'></i>");
document.writeln("                <a href=\'#\'  class=\'bg\'>解决方案</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'mine\'> ");
document.writeln("                <i class=\'is\'></i>");
document.writeln("                <a href=\'#\'  class=\'bg\'>关于我们</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\'box\'>");
document.writeln("            <ul class=\'rightcontainer box1\'>");
document.writeln("                <li>");
document.writeln("                    <img src=\'../images/headerimages/蒙版组 306@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>数字化客户经营</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'../images/headerimages/蒙版组 312@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>私域互动经营</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'../images/headerimages/蒙版组 313@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'http://127.0.0.1:5500/html/Customerportrait.html\' class=\'tuan\'>数据中台</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'rightcontainer box2\'>");
document.writeln("                <li>     ");
document.writeln("                    <a href=\'#\' class=\'teshu\'>场景解决方案</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                     <img src=\'../images/headerimages/蒙版组 440@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>营销自动化</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'../images/headerimages/蒙版组 441@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'http://127.0.0.1:5500/html/privatePool.html\' class=\'tuan\'>私域流量池</a></li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'/images/headerimages/蒙版组 462@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>客户画像</a></li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'/images/headerimages/蒙版组 463@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>数据分析</a></li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'/images/headerimages/蒙版组 444@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>生命周期管理</a></li>");
document.writeln("                <li>");
document.writeln("                    <img src=\'/images/headerimages/蒙版组 441@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                    <a href=\'#\' class=\'tuan\'>私有化与定制</a></li>");
document.writeln("                <li>");
document.writeln("                        <a href=\'#\' class=\'teshu\'>行业解决方案</a></li>");
document.writeln("                <li>");
document.writeln("                        <img src=\'/images/headerimages/蒙版组 448@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                         <a href=\'#\' class=\'tuan\'>康养解决方案</a></li>");
document.writeln("    ");
document.writeln("                <li>");
document.writeln("                        <img src=\'/images/headerimages/蒙版组 465@2x.png\' width=\'20px\' height=\'20px\' alt=\'\'>");
document.writeln("                        <a href=\'#\' class=\'tuan\'>新零售解决方案</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("");
document.writeln("    ");
document.writeln("        ");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("");
document.writeln("   </div>");
document.writeln("   ");
document.writeln("</body>");
document.writeln("<script>");
document.writeln("    window.addEventListener(\'load\',function(){");
document.writeln("    var subnav=document.querySelector(\'.subnav\');");
document.writeln("    var btn=document.querySelector(\'.btn2\');");
document.writeln("    var tab_list=document.querySelector(\'.subnavleft\');");
document.writeln("    console.log(tab_list);");
document.writeln("    ");
document.writeln("");
document.writeln("   var lis=tab_list.querySelectorAll(\'li\');");
document.writeln("   console.log(lis);");
document.writeln("    var index=document.querySelector(\'.index\');");
document.writeln("    var mine=document.querySelector(\'.mine\');");
document.writeln("    var produce=document.querySelector(\'.product\');");
document.writeln("    var deal=document.querySelector(\'.deal\');");
document.writeln("    var box1=document.querySelector(\'.box1\')");
document.writeln("    var box2=document.querySelector(\'.box2\')");
document.writeln("    var flag=0;");
document.writeln("    btn.addEventListener(\'click\',function(){");
document.writeln("        if(flag==0){");
document.writeln("             subnav.style.display=\'block\'; ");
document.writeln("             subnav.style.display=\'flex\'; ");
document.writeln("            flag=1;");
document.writeln("            for(var i=0;i<lis.length;i++){");
document.writeln("                    lis[i].onclick=function(){");
document.writeln("                        for(var i=0;i<lis.length;i++){");
document.writeln("                            lis[i].className=\'\';");
document.writeln("                        }");
document.writeln("                         this.className=\'current\';");
document.writeln("           }}");
document.writeln("                            index.addEventListener(\'click\',function(){");
document.writeln("                                box1.style.display=\'none\';");
document.writeln("                                box2.style.display=\'none\';");
document.writeln("                            ");
document.writeln("                            })");
document.writeln("                            produce.addEventListener(\'click\',function(){");
document.writeln("                                        box1.style.display=\'block\';");
document.writeln("                                        box2.style.display=\'none\';");
document.writeln("                                      ");
document.writeln("                                    ");
document.writeln("                                    });");
document.writeln("                            deal.addEventListener(\'click\',function(){          ");
document.writeln("                                        box2.style.display=\'block\';");
document.writeln("                                        box1.style.display=\'none\';");
document.writeln("                                     ");
document.writeln("                            });");
document.writeln("                            mine.addEventListener(\'click\',function(){");
document.writeln("                                box1.style.display=\'none\';");
document.writeln("                                box2.style.display=\'none\';");
document.writeln("                               ");
document.writeln("                    });");
document.writeln("                ");
document.writeln("            ");
document.writeln("        }else{");
document.writeln("            subnav.style.display=\'none\'; ");
document.writeln("            flag=0;");
document.writeln("            }");
document.writeln("    })");
document.writeln("");
document.writeln("})");
document.writeln("");
document.writeln("");
document.writeln("</script>");
document.writeln("</html>");