document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("  <meta charset=\'UTF-8\'>");
document.writeln("  <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("  <title>错误格式</title>");
document.writeln("  <link rel=\'stylesheet\' href=\'../css/dialog_root.css\'>");
document.writeln(" ");
document.writeln("  <script src=\'../jquery-3.6.0.js\'></script>");
document.writeln("  <script src=\'../js/dialog_root.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  <div>");
document.writeln("    <div class=\'login-error-dialog-root\'>");
document.writeln("      <div class=\'login-error-dialog-mask\'>");
document.writeln("        <div class=\'login-error-dialog-wrap\'>");
document.writeln("          <div role=\'docuement\' class=\'login-error-dialog\'>");
document.writeln("            <div class=\'login-error-dialog-content\'>");
document.writeln("              <div class=\'login-error-dialog-body\'></div>");
document.writeln("              <div class=\'login-error-dialog-mag\'>");
document.writeln("                手机格式不正确，请重新输入");
document.writeln("              </div>");
document.writeln("              <div class=\'login-error-dialog-ok-btn\'>");
document.writeln("                确认");
document.writeln("              </div>");
document.writeln("        ");
document.writeln("            </div>");
document.writeln("");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</body>");
document.writeln("</html>");