document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>尾部文件</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/fotter.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'information\'>");
document.writeln("    </div>");
document.writeln("    <div class=\'local1\'>");
document.writeln("        <div class=\'local_nav\'>");
document.writeln("            <ul class=\'local_navleft\'>");
document.writeln("                <li>产品</li>");
document.writeln("                <li>数字化客户经营</li>");
document.writeln("                <li>数据中台</li>");
document.writeln("                <li>企微SCRM</li>");
document.writeln("                <li>行业解决方案</li>");
document.writeln("                <li>康养解决方案</li>");
document.writeln("                <li>新零售解决方案</li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'local_navleft local_navright\'>");
document.writeln("                <li>场景解决方案</li>");
document.writeln("                <li>全域营销自动化</li>");
document.writeln("                <li>私域流量池</li>");
document.writeln("                <li>数据分析</li>");
document.writeln("                <li>生命周期管理</li>");
document.writeln("                <li>私有化定制</li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'local2\'>");
document.writeln("            <p class=\'local2txt1\'>");
document.writeln("                <span class=\'spa1\'>关于我们</span>");
document.writeln("                <span class=\'spa2\'>关于我们</span>");
document.writeln("            </p>");
document.writeln("            <p class=\'local2txt2\'>文章资讯</p>");
document.writeln("            <p class=\'local2txt2\'>行业洞察</p>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'local3\'>");
document.writeln("            <div class=\'local3_1\'>");
document.writeln("                <span class=\'local3_sp1\'>咨询热线：</span>");
document.writeln("                <span class=\'local3_sp2\'>15018504813</span>");
document.writeln("            </div>");
document.writeln("            <div class=\'local3_2\'>");
document.writeln("                <span class=\'local3_sp1\'>邮箱：</span>");
document.writeln("                <span class=\'local3_sp2\'>mangolee@gymoo.cn</span>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    <div class=\'lastnav\'>版权所有：<br>");
document.writeln("        Copyright深圳市积木创意科技有限公司粤ICP备1705xxxx号-11</div>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("</html>");