document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>客户画像</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/Customerportrait.css\'>");
document.writeln("    <script src=\'../js/ Customer portrait.js\'></script>");
document.writeln("    <script src=\'../swiper/swiper-bundle.min.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'./bootstrap/css/bootstrap.css\'>");
document.writeln("    <script src=\'../html/header1.html\'></script>");
document.writeln("    <script src=\'../jquery-3.6.0.js\'></script>");
document.writeln("    <script src=\'../bootstrap/js/bootstrap.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../swiper/swiper-bundle.min.css\'>");
document.writeln("    ");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("        <!-- <div class=\'header\'>");
document.writeln("            <div class=\'logo\'>");
document.writeln("                <span>");
document.writeln("                    <button class=\'glyphicon glyphicon-menu-hamburger\'></button>");
document.writeln("                </span>");
document.writeln("                <span>");
document.writeln("                    <img src=\'../images/images_product/logo@2x.png\' alt=\'\'>");
document.writeln("                </span>");
document.writeln("                <span></span>");
document.writeln("            </div>");
document.writeln("            <div class=\'logotxt1\'>企业微信<br>");
document.writeln("                私域解决方案");
document.writeln("            </div>");
document.writeln("            <div class=\'logotxt2\'>");
document.writeln("                获客、客户经营、客户转化");
document.writeln("                的一体化解决方案");
document.writeln("            </div>");
document.writeln("            <div class=\'btn\'>");
document.writeln("                免费试用");
document.writeln("            </div>");
document.writeln("        </div> -->");
document.writeln("        <div class=\'xitong_nav\'>");
document.writeln("            <div class=\'xitong_nav_box\'>");
document.writeln("                <img src=\'../images/images_product/left.png\' alt=\'\'>");
document.writeln("                <p class=\'title\'>用数字化能力助力品牌洞察客户画像</p>");
document.writeln("                <img src=\'../images/images_product/right.png\' alt=\'\'>");
document.writeln("         ");
document.writeln("            </div>");
document.writeln("            <p class=\'smalltitle\'>基于企业沉淀的数据，利用智能标签与数据分析，构建客户全景画像</p>");
document.writeln("            <div class=\'xitong-icon\'>");
document.writeln("                <img src=\'../images/客户画像imgaes/画板 – 10@2x.png\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <p class=\'xitong_search\'>");
document.writeln("                【查看大图】");
document.writeln("            </p>");
document.writeln("            <p class=\'title myp\'>积木云策如何构建全景画像</p>");
document.writeln("        <div class=\'body_nav1\'>");
document.writeln("           <div class=\'body_nav1_icon icon0\'>");
document.writeln("           </div>");
document.writeln("         <div class=\'leftnav_icon\'>");
document.writeln("    ");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'box1 box1_shuju\'>");
document.writeln("            <p class=\'box1_txt1 box1_quanqu\'>全渠道数据治理</p>");
document.writeln("           <div class=\'box1_nav\'>");
document.writeln("                <p class=\'box1_nav_txt1\'>利用数据对接，从品牌线上线下所有渠道中获取客户数据源。利用数据清洗能力沉淀品牌客户数据资产 </p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'box1_nav2\'>");
document.writeln("            <div class=\'body_nav1_icon icon1\'>");
document.writeln("            </div>");
document.writeln("          <div class=\'leftnav_icon right_icon\'>");
document.writeln("         </div>");
document.writeln("         </div>");
document.writeln("         <div class=\'box1\'>");
document.writeln("             <p class=\'box1_txt1 box1_yonhu\'>构建用户画像</p> ");
document.writeln("             <div class=\'box1_nav box_nav2\'>");
document.writeln("                 <p class=\'box1_nav_txt1\'>");
document.writeln("                    <span>智能标签：</span>");
document.writeln("                    基于客户行为构建消费者智能标签");
document.writeln("                   </p>");
document.writeln("             </div>");
document.writeln("             <div class=\'box1_nav box_nav3\'>");
document.writeln("                <p class=\'box1_nav_txt1\'>");
document.writeln("                   <span> 客户分层：</span>");
document.writeln("                    通过多纬度的客户画像与业务行为，自定义智能化客户分层</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'box1_nav box_nav4\'>");
document.writeln("                <p class=\'box1_nav_txt1\'>");
document.writeln("                  <span>客户透视：</span>");
document.writeln("                    基于数据能力输出360度客户画像</p>");
document.writeln("            </div>");
document.writeln("         </div> ");
document.writeln("         <div class=\'body_nav1\'>");
document.writeln("            <div class=\'body_nav1_icon icon2\'>");
document.writeln("            </div>");
document.writeln("          <div class=\'leftnav_icon\'>");
document.writeln("     ");
document.writeln("         </div>");
document.writeln("         </div>");
document.writeln("         <div class=\'box1\'>");
document.writeln("             <p class=\'box1_txt1 box1_fenxi\'>用户画像分析</p>");
document.writeln("             <div class=\'box1_nav\'>");
document.writeln("                 <p class=\'box1_nav_txt1\'>用户属性、用户来源、业务行为、用户消费、用户标签…..");
document.writeln("                    基于品牌业务与顾客特征，产出全景画像报告 </p>");
document.writeln("             </div>");
document.writeln("         </div>");
document.writeln("         <div class=\'body_nav1\'>");
document.writeln("            <div class=\'body_nav1_icon icon3\'>");
document.writeln("            </div>");
document.writeln("          <div class=\'leftnav_icon right_icon\'>");
document.writeln("     ");
document.writeln("         </div>");
document.writeln("         </div>");
document.writeln("         <div class=\'box1\'>");
document.writeln("             <p class=\'box1_txt1\'>用户画像应用</p>");
document.writeln("             <div class=\'box1_nav\'>");
document.writeln("                 <p class=\'box1_nav_txt1\'>用户画像赋能精准营销、客户运营与数据分析。帮助企业发现业务经营中的潜在增长点，实现知客懂客，增长有策的数字化运营");
document.writeln("                </p>");
document.writeln("             </div>");
document.writeln("         </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'information\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'local1\'>");
document.writeln("            <div class=\'local_nav\'>");
document.writeln("                <ul class=\'local_navleft\'>");
document.writeln("                    <li>产品</li>");
document.writeln("                    <li>数字化客户经营</li>");
document.writeln("                    <li>数据中台</li>");
document.writeln("                    <li>企微SCRM</li>");
document.writeln("                    <li>行业解决方案</li>");
document.writeln("                    <li>康养解决方案</li>");
document.writeln("                    <li>新零售解决方案</li>");
document.writeln("                </ul>");
document.writeln("                <ul class=\'local_navleft local_navright\'>");
document.writeln("                    <li>场景解决方案</li>");
document.writeln("                    <li>全域营销自动化</li>");
document.writeln("                    <li>私域流量池</li>");
document.writeln("                    <li>数据分析</li>");
document.writeln("                    <li>生命周期管理</li>");
document.writeln("                    <li>私有化定制</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'local2\'>");
document.writeln("                <p class=\'local2txt1\'>");
document.writeln("                    <span class=\'spa1\'>关于我们</span>");
document.writeln("                    <span class=\'spa2\'>关于我们</span>");
document.writeln("                </p>");
document.writeln("                <p class=\'local2txt2\'>文章资讯</p>");
document.writeln("                <p class=\'local2txt2\'>行业洞察</p>");
document.writeln("    ");
document.writeln("            </div>");
document.writeln("            <div class=\'local3\'>");
document.writeln("                <div class=\'local3_1\'>");
document.writeln("                    <span class=\'local3_sp1\'>咨询热线：</span>");
document.writeln("                    <span class=\'local3_sp2\'>15018504813</span>");
document.writeln("                </div>");
document.writeln("                <div class=\'local3_2\'>");
document.writeln("                    <span class=\'local3_sp1\'>邮箱：</span>");
document.writeln("                    <span class=\'local3_sp2\'>mangolee@gymoo.cn</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        <div class=\'lastnav\'>版权所有：<br>");
document.writeln("            Copyright深圳市积木创意科技有限公司粤ICP备1705xxxx号-11</div>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            手机号码：");
document.writeln("            <input type=\'text\'>");
document.writeln("            <button>提交</button>");
document.writeln("        </div>");
document.writeln("    </body>");
document.writeln("</html>");